[package]
name = "chain"
version = "0.3.0"
authors = ["j-n-f <j-n-f@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
ron = "*"
dirs = "2.0"
pancurses = "0.16"
